name: Linux images

on:
  workflow_dispatch:
    inputs:
      images:
        type: string
        required: true
        description: 'Distribution(s) to build'
        default: '["ubuntu22-full-x64", "ubuntu22-full-arm64", "ubuntu24-full-x64", "ubuntu24-full-arm64", "ubuntu26-full-x64", "ubuntu26-full-arm64"]'
  schedule:
    - cron: '0 8 2,17 * *'

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      release_prefix: linux
      ami_cleanup_prefix: runs-on-dev-ubuntu
      dist_prefix: ubuntu

  build-test-release:
    name: Build/Test/Release ${{ matrix.image_id }}
    needs: sync
    strategy:
      fail-fast: false
      matrix:
        image_id: ${{ fromJSON(github.event.inputs.images || '["ubuntu22-full-x64", "ubuntu22-full-arm64", "ubuntu24-full-x64", "ubuntu24-full-arm64", "ubuntu26-full-x64", "ubuntu26-full-arm64"]') }}
    uses: ./.github/workflows/build-test-release.yml
    secrets: inherit
    with:
      image_id: ${{ matrix.image_id }}
      platform: linux

  generate-release:
    needs:
      - sync
      - build-test-release
    uses: ./.github/workflows/generate-release.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      release_name: ${{ needs.sync.outputs.release_name }}
